export const TISTORY_URLS = {
  login: 'https://www.tistory.com/auth/login',
  home: 'https://www.tistory.com/',
  manage: 'https://www.tistory.com/',
  write: (blogName: string) => `https://${blogName}.tistory.com/manage/newpost`,
  category: (blogName: string) => `https://${blogName}.tistory.com/manage/category`,
  // 📋 생성된 글목록 탭 — 관리 화면 글 목록 / 기존 글 편집 / 공개 글 주소
  managePosts: (blogName: string, page = 1) => `https://${blogName}.tistory.com/manage/posts?page=${page}`,
  editPost: (blogName: string, postId: string) => `https://${blogName}.tistory.com/manage/newpost/${postId}`,
  entry: (blogName: string, postId: string) => `https://${blogName}.tistory.com/${postId}`,
};

export const TISTORY_SELECTORS = {
  login: {
    kakaoLoginButtons: [
      'a[href*="kakao"]',
      'button:has-text("\\uCE74\\uCE74\\uC624")',
      'a:has-text("\\uCE74\\uCE74\\uC624")',
      'text=\\uCE74\\uCE74\\uC624\\uACC4\\uC815\\uC73C\\uB85C \\uB85C\\uADF8\\uC778',
    ],
  },
  home: {
    writeLinks: [
      'a.link_tab[href*="/manage/newpost"]',
      'a[href*=".tistory.com/manage/newpost"]',
    ],
  },
  editor: {
    introModalCloseButtons: [
      '.layer_post_intro .btn_close',
      '.layer_post_intro button:has-text("\\uB2EB\\uAE30")',
      'button:has-text("\\uB2EB\\uAE30")',
      'button[aria-label="\\uB2EB\\uAE30"]',
    ],
    titleInputs: [
      'textarea#post-title-inp',
      '#post-title-inp',
      'textarea[placeholder*="\\uC81C\\uBAA9"]',
      'input[placeholder*="\\uC81C\\uBAA9"]',
      '[contenteditable="true"][data-placeholder*="\\uC81C\\uBAA9"]',
    ],
    modeButtons: [
      '#editor-mode-layer-btn-open',
      '[data-button-type="mode"]',
      'button:has-text("\\uAE30\\uBCF8\\uBAA8\\uB4DC")',
      'button:has-text("\\uB9C8\\uD06C\\uB2E4\\uC6B4")',
      'button:has-text("HTML")',
      '.editor-mode button',
    ],
    htmlModeButtons: [
      '#editor-mode-html',
      '#editor-mode-html-text',
      'button:has-text("HTML")',
      '[role="menuitem"]:has-text("HTML")',
      'li:has-text("HTML")',
      'text=HTML',
    ],
    htmlEditors: [
      '#html-editor',
      'textarea#html-editor',
      'textarea[name="html"]',
      'textarea[data-mode="html"]',
      'textarea.tx-source',
      'textarea.CodeMirror-code',
      '.CodeMirror textarea',
      '.cm-content[contenteditable="true"]',
    ],
    richEditors: [
      '.contents_style[contenteditable="true"]',
      '.editor-content[contenteditable="true"]',
      '[contenteditable="true"]',
      'iframe',
    ],
    imageUploadButtons: [
      'button[aria-label*="사진"]',
      'button[title*="사진"]',
      'button[aria-label*="이미지"]',
      'button[title*="이미지"]',
      'button[aria-label*="그림"]',
      'button[title*="그림"]',
      'button[aria-label*="Image"]',
      'button[title*="Image"]',
      '[role="button"][aria-label*="사진"]',
      '[role="button"][title*="사진"]',
      '.mce-i-image',
      '.mce-i-photo',
      '.mce-i-picture',
      '[class*="image" i]',
      '[class*="photo" i]',
    ],
    imageFileInputs: [
      'input[type="file"][accept*="image"]',
      'input[type="file"][accept*="png"]',
      'input[type="file"][accept*="jpg"]',
      'input[type="file"][accept*="jpeg"]',
      'input[type="file"]',
    ],
    categoryTriggers: [
      'button#category-btn',
      '[data-category-trigger]',
      'button:has-text("\\uCE74\\uD14C\\uACE0\\uB9AC")',
      '.category button',
    ],
    tagInputs: [
      'input#tagText',
      'input[placeholder*="\\uD0DC\\uADF8"]',
      '.tag_post input',
    ],
    tempSaveButtons: [
      '#temp-save-btn',
      '#save-btn',
      '#save-button',
      '#draft-btn',
      'button[id*="save"]',
      'button[id*="draft"]',
      'button[class*="save"]',
      '.btn_save',
      '.btn-draft',
      'button:has-text("\\uC784\\uC2DC\\uC800\\uC7A5")',
      'button:has-text("\\uC800\\uC7A5")',
      'button#temp-save-btn',
    ],
    publishButtons: [
      '#publish-layer-btn',
      'button#publish-layer-btn',
    ],
    publishConfirmButtons: [
      '#publish-btn',
      '.layer_publish #publish-btn',
      'button#publish-btn',
      '.layer_publish button:has-text("\\uBC1C\\uD589")',
      '.layer_publish button:has-text("\\uACF5\\uAC1C \\uBC1C\\uD589")',
      'button:has-text("\\uACF5\\uAC1C \\uBC1C\\uD589")',
      'button:has-text("\\uBC1C\\uD589")',
    ],
    // 기존 글 수정발행 시 확인 버튼 — 새 글은 "발행", 수정은 "수정"으로 라벨이 바뀐다
    updateConfirmButtons: [
      '#publish-btn',
      '.layer_publish #publish-btn',
      'button#publish-btn',
      '.layer_publish button:has-text("수정")',
      '.layer_publish button:has-text("공개 발행")',
      '.layer_publish button:has-text("발행")',
      'button:has-text("수정")',
      'button:has-text("발행")',
    ],
    visibility: {
      public: [
        'input[name="visibility"][value="20"]',
      ],
      private: [
        'input[name="visibility"][value="0"]',
      ],
      protected: [
        'input[name="visibility"][value="15"]',
      ],
    },
  },
};
